language: csharp
os: linux
dist: focal
mono: none
dotnet: 6.0

git:
  depth: false

install:
   - dotnet tool install --global dotnet-sonarscanner
   - dotnet restore

script:
   - dotnet sonarscanner begin /k:"nullfx_NullFX.CRC" /o:"nullfx" /d:sonar.login="dO8T9aL3xOW7VGmISJutic3fooLUWaFB+2T1ZMQYkUmXhBow7CaFXsxqtWPPe3ERqdGck3aFKubwpLiB3lfTzvb257wFXaYJopad25a4oDgEi4mmY/g1oD9VXuGzcEPQsXvLrC525AwXd2K8d2IBWiYr2HYIiwAIF8ZvSs/4B2hueZwqDriFph0peXxjq/ZtcpvxzS9gvtAmCuEhSwGrulGXwQjIceTpWRmgJivnyQeEQ4RVvX6XkmGcVCGyzvjG5q4xL3ve0nFyXbu5asCXWvMwrujqN4C9eK9+LZxz7GS8IxP19ozOHhAnucX8EY41osFk9DewQxIKddKS+A1CxmOxs9VusZFl1REwBn4YJ+phqfAZLguBu/sdZcK9CA4NSLyHdro7NMe5nJBocLHLJ4tfncidUkALLITfrKc7TIJaZM55cwICrOnfgNjDE/JyBwghmyk4AmDlpfoLk7bWb+Zh/lUwslZPfQ9tpgEsuhomJtDlbkP7oGnmEEyYCdmL4ZjUpLqt7YVBZCMhcJvK1LV2duxYQuDzijL5eWN1U5hRJh1t7LtakwpecghKl9Sbv6ERgqWKuIlDH3Hjc7cJc5jyXpxpag/aw+QK1yPkH0g1bN702urXvGvEmHTlfV9lNdUs+wYuAi3vZlky9Or/UKU0K3DfrqtyCFzTZ3gfWxY="
   - dotnet build NullFX.CRC/NullFX.CRC.csproj
   - dotnet test NullFX.CRC.Tests/NullFX.CRC.Tests.csproj
   - dotnet sonarscanner end /d:sonar.login="dO8T9aL3xOW7VGmISJutic3fooLUWaFB+2T1ZMQYkUmXhBow7CaFXsxqtWPPe3ERqdGck3aFKubwpLiB3lfTzvb257wFXaYJopad25a4oDgEi4mmY/g1oD9VXuGzcEPQsXvLrC525AwXd2K8d2IBWiYr2HYIiwAIF8ZvSs/4B2hueZwqDriFph0peXxjq/ZtcpvxzS9gvtAmCuEhSwGrulGXwQjIceTpWRmgJivnyQeEQ4RVvX6XkmGcVCGyzvjG5q4xL3ve0nFyXbu5asCXWvMwrujqN4C9eK9+LZxz7GS8IxP19ozOHhAnucX8EY41osFk9DewQxIKddKS+A1CxmOxs9VusZFl1REwBn4YJ+phqfAZLguBu/sdZcK9CA4NSLyHdro7NMe5nJBocLHLJ4tfncidUkALLITfrKc7TIJaZM55cwICrOnfgNjDE/JyBwghmyk4AmDlpfoLk7bWb+Zh/lUwslZPfQ9tpgEsuhomJtDlbkP7oGnmEEyYCdmL4ZjUpLqt7YVBZCMhcJvK1LV2duxYQuDzijL5eWN1U5hRJh1t7LtakwpecghKl9Sbv6ERgqWKuIlDH3Hjc7cJc5jyXpxpag/aw+QK1yPkH0g1bN702urXvGvEmHTlfV9lNdUs+wYuAi3vZlky9Or/UKU0K3DfrqtyCFzTZ3gfWxY="
