name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
#        fetch-depth: 0
#     - name: SonarCloud Scan
#       uses: highbyte/sonarscan-dotnet@v2.1.2
#       with:
#         sonarProjectKey: nullfx_NullFX.CRC
#         sonarProjectName:  NullFX.CRC
#         sonarOrganization: nullfx
#         dotnetDisableTests: true
#       env:
#         GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: install dependencies
      run: dotnet restore      
    - name: build
      run: dotnet build --no-restore      
    - name: test
      run: dotnet test --no-build --verbosity normal
